### ISSUE TITLE
Packaged addon

### ISSUE THREAD

**Issue by Kazlehoff** [Kayakflo/wow-dialogkey-sl#1]
Hey, i was speaking with Acidweb, who makes the CurseBreaker mod manager. i was trying to use the addon manager to add your addon. it does not add, as it is not a packaged addon.

when speaking with Acidweb about this, he let me know that for addons to be added with addon managers, Packaged releases need to be made, with something like the BigWigs Packager (https://github.com/BigWigsMods/packager)

would it be possible for you to package your addon?

thanks

**Comment by Kayakflo** [comment]
@Kazlehoff Done!
I have uploaded a packaged version of the addon as a release artifact.
The installation worked using `CB> install https://github.com/Kayakflo/wow-dialogkey-sl`.
Do I need to do anything else in order to support CB?

Please be aware that this Addon was not created by me. I just made the Shadowlands adjustments.

**Comment by icbat** [comment]
I can confirm that this is all you need to be able to install via CurseBreaker :)

**Comment by Kazlehoff** [comment]
Shoot I forgot to reply. Yup, the Packaged version works.
